### ISSUE TITLE
Only getting first char when populating Text - Here's the fix

### ISSUE THREAD

**Issue by bakertony** [akorb/PlaceholderTextBox#1]
Hi, in PlaceholderTextBox_TextChanged, you need to change:

```
// Throw away the placeholder but leave the new typed char
Text = Text[0].ToString();
```

to:

```
// Throw away the placeholder but leave the new typed char
Text = Text.Replace(PlaceholderText, "");
```

Otherwise, when I populate the empty Text parameter in my code with a string, I'm only getting the first char of the string!

**Comment by akorb** [comment]
Thank you very much!
You are totally right, that was an issue. I just fixed it with a slightly different solution you offered.
With your solution, the new inserted Text might be trimmed by any appearance of the placeholder.

:)
